### ISSUE TITLE
Usage example fails with "Error : XML content does not seem to be XML"

### ISSUE THREAD

**Issue by jefdaj** [MVesuviusC/primerTree#19]
I tried the example "Simple search for a Mammal 16S primer", but `search_primer_pair` fails and returns the full HTML of the search page instead. It says:

BLASTing 1 primer combinations
Error : XML content does not seem to be XML: 'search page HTML here'

**Comment by jefdaj** [comment]
Never mind, I was using the version from CRAN. Current HEAD retrieves the results fine. But now I'm unable to plot them with `plot(mammals_16S)`. I just get a blank plot window.

**Comment by MVesuviusC** [comment]
Do your other plot functions work as well? You may need to dev.off() a couple of times perhaps?

**Comment by jefdaj** [comment]
Sorry I think I created an issue before trying hard enough to solve this! After looking through the source a little it works great. The documentation just needs to be adjusted to say that you specify a rank in the plot call, like `rank='phylum'`. Otherwise it prints the possibilities and doesn't plot anything.

**Comment by MVesuviusC** [comment]
Hmm, ok. Plot(mammals_16S) should work though. You shouldn't need to specify rank, there are default ranks that should be plotted. If you're getting something like this you may need to update to the newest version of primerTree:

TableGrob (3 x 3) "arrange": 8 grobs
          z     cells    name           grob
structure 1 (1-1,1-1) arrange gtable[layout]
kingdom   2 (1-1,2-2) arrange gtable[layout]
phylum    3 (1-1,3-3) arrange gtable[layout]
class     4 (2-2,1-1) arrange gtable[layout]
order     5 (2-2,2-2) arrange gtable[layout]
family    6 (2-2,3-3) arrange gtable[layout]
genus     7 (3-3,1-1) arrange gtable[layout]
species   8 (3-3,2-2) arrange gtable[layout]
