### ISSUE TITLE
Error in UseMethod("xpathApply")

### ISSUE THREAD

**Issue by cruckert** [MVesuviusC/primerTree#20]
Running 

`search_primer_pair("GAACATGTCAAAGTCACTGGACTTCATGG", "ATATATGTGTTACCTACCCTTGTCGGTCC", "test1")`

I got the following error

`Error in UseMethod("xpathApply") : no applicable method for 'xpathApply' applied to an object of class "c('xml_document', 'xml_node')"`

According to: [](http://stackoverflow.com/questions/35479549/error-in-r-no-applicable-method-for-xpathapply) this is due to some changes in the current version (1.1.0) of httr.

My workaround was to install an older version (1.0.0)

**Comment by jimhester** [comment]
What version of primerTree are you using? CRAN version 1.0.3 fixes this as does the development version here on GitHub. You may need to run `update.packages()` to get the latest released version.

**Comment by dcallander** [comment]
I'm having the same problem.

Error in UseMethod("xpathApply") : 
  no applicable method for 'xpathApply' applied to an object of class "c('xml_document', 'xml_node')"

primerTree version 1.0.3, all packages updated. R version 3.2.4. windows.
Thanks.

**Comment by jmcraine** [comment]
Same problem for me. tried both 1.0.0 and 1.0.3 versions. Running 3.2.5 on mac. any guidance would be helpful.

**Comment by MVesuviusC** [comment]
Hey Jim, I'm also seeing this issue. I updated my R and Rstudio to the latest versions and updated all the packages. Still seeing the same message...

`

> get_taxonomy(555)

No encoding supplied: defaulting to UTF-8.
Error in UseMethod("xpathApply") : 
  no applicable method for 'xpathApply' applied to an object of class "c('xml_document', 'xml_node')"
In addition: Warning messages:
1: In POST_retry(url, body = query) : request failed, retry attempt 1
2: In POST_retry(url, body = query) : request failed, retry attempt 2
3: In POST_retry(url, body = query) : request failed, retry attempt 3
4: In POST_retry(url, body = query) : request failed, retry attempt 4
5: In POST_retry(url, body = query) : request failed, retry attempt 5

> sessionInfo()

R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] primerTree_1.0.3        gridExtra_2.2.1         directlabels_2015.12.16

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.4      lubridate_1.5.6  quadprog_1.5-5   lattice_0.20-33  ape_3.4          codetools_0.2-14 XML_3.98-1.4     foreach_1.4.3  
 [9] R6_2.1.2         plyr_1.8.3       grid_3.3.0       nlme_3.1-127     gtable_0.2.0     magrittr_1.5     scales_0.4.0     httr_1.1.0  
[17] ggplot2_2.1.0    stringi_1.0-1    curl_0.9.7       xml2_0.1.2       iterators_1.0.8  tools_3.3.0      stringr_1.0.0    munsell_0.4.3  
[25] colorspace_1.2-6

> `

**Comment by jimhester** [comment]
Closed by #21
