### ISSUE TITLE
primerTree polls NCBI too frequently

### ISSUE THREAD

**Issue by taltman** [MVesuviusC/primerTree#24]
To avoid running afoul of NCBI's servers and getting blocked, primerTree should poll only once a minute for results, not every 20 seconds:

https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=DeveloperInfo

It also mentions no more than 20 searches in a session (unless on the weekends or evenings), but that seems to be something that the user has to be aware of, and restrict their usage accordingly.

**Comment by jimhester** [comment]
The refresh rate is coming from the response metadata (https://github.com/jimhester/primerTree/blob/59369a571fdb150b539fa0d43dd1f84c8a180aa9/R/search.R#L200-L208), so is controlled by NCBI directly.

Also that documentation is for the NCBI Rest service, which primerTree predates by a number of years. PrimerTree queries and parses the regular web interface to Primer-BLAST.
