### ISSUE TITLE
 Warning messages:  1: In GET_retry &  Error in `[.data.frame`(hits, location_columns) : undefined columns selected

### ISSUE THREAD

**Issue by Matthias-LIB** [MVesuviusC/primerTree#26]
Dear colleague, 
I am struggling running primerTree. Even when using the simple test 

mammals_16S = search_primer_pair(name='Mammals 16S', 'CGGTTGGGGTGACCTCGGA', 'GCTGTTATCCCTAGGGTAACT')

I get lots of warnings

 > warnings()
Warning messages:
1: In GET_retry(url) : request failed, retry attempt 1
2: In GET_retry(url) : request failed, retry attempt 2
3: In GET_retry(url) : request failed, retry attempt 3
4: In GET_retry(url) : request failed, retry attempt 4
5: In GET_retry(url) : request failed, retry attempt 5
6: In POST_retry(paste(url, "primertool.cgi", sep = ""),  ... :
  request failed, retry attempt 1
7: In POST_retry(paste(url, "primertool.cgi", sep = ""),  ... 
  request failed, retry attempt 2

and at the end an error:
Error in `[.data.frame`(hits, location_columns) : undefined columns selected

Is this a known bug and a solution known? I am running R 331 and R 332 on another machine. Any help would be great. 

cheers,
Matthias

**Comment by ray1919** [comment]
I got the same error msg using the test code

**Comment by jimhester** [comment]
Should now be fixed.
