### ISSUE TITLE
latest version of XML issue

### ISSUE THREAD

**Issue by PWSmit** [MVesuviusC/primerTree#27]
Hi, 

seems when updating to the latest version of XML (to 3.98-1.6), an issue arrises when using search_primer_pair function, downloaded via devtools, not CRAN. Giving the following error: 

error: XML content does not seem to be XML: 'NA'

**Comment by bestfishes** [comment]
I'm having the same issue - is there a fix for this?

Specifically, it looks like response = POST_retry in BLAST_primer is immediately being returned with a status category of success (and thus is passing the retry checks), but page content is NA. Not sure if this is an XML issue or if something changed with NCBI?

**Comment by jimhester** [comment]
This should now be fixed.
