### ISSUE TITLE
NCBI rate-limiting e-utilities queries, causing HTTP 429

### ISSUE THREAD

**Issue by MVesuviusC** [MVesuviusC/primerTree#33]
NCBI is now rate limiting eutilities queries, which has been causing errors for PrimerTree. During the get_sequences() portion of the search_primer_pair() function I was getting this error:

```
Error in get_sequence(gi[i], start[i], stop[i], api_key) :
  Too Many Requests (RFC 6585) (HTTP 429).
In addition: Warning messages:
1: In get_sequence(gi[i], start[i], stop[i], api_key) :
2: In POST_retry(fetch_url, body = query) :
  request failed, retry attempt 1
3: In POST_retry(fetch_url, body = query) :
  request failed, retry attempt 2
4: In POST_retry(fetch_url, body = query) :
  request failed, retry attempt 3
5: In POST_retry(fetch_url, body = query) :
  request failed, retry attempt 4
6: In POST_retry(fetch_url, body = query) :
  request failed, retry attempt 5
```

I made the get_sequence() function output the response variable for each query and when I do I get this message:

```
{"error":"API rate limit exceeded","api-key":"134.192.135.254","count":"17","limit":"3"}
```

So, in essence, PrimerTree queries the NCBI's servers too quickly. Especially if the query takes too long and the request is retried in the retry_POST() function, the servers can essentially get five queries in quick succession due to the way the POST_retry() function works. Since they just implemented their rate limiting and api-keys, this is a problem. https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/

There are two main ways to go about fixing this. Instead of getting one sequence at a time, we could get them in batches. However, when downloading only the portion of the sequence that we need using the "start" and "stop" arguments in the efetch address, you cannot get more than one sequence at a time. So this method would require downloading the entire sequence instead of just the portion hit by BLAST. Since the sequence could be huge, we'd be transferring tons of useless data, so this approach is likely not a good option.

The alternative is to limit the query rate to allowable limits. This is 3 queries per second, unless you provide an api-key, then 10 queries per second are allowed (or more if you negotiate with NCBI). I've worked on implementing an "api_key" argument and limiting the get_sequences() query rate to 3 unless an api-key is provided, then 10 queries per second are allowed. I also put "Sys.sleep(0.4)" inside the retry() function to keep it from slamming the NCBI servers in case the query isn't retrieved quickly enough.

With these changes, PrimerTree works normally (but slower) and the NCBI rate limit isn't hit. I put in a warning message if an api-key isn't provided instructing the user to get an api-key to make it go faster. We might consider adding a rate_limit argument to allow people to specify a custom query rate in case they get permission from NCBI for more than 10 requests per second.

Slowing the sequence retrieval down is a sub-optimal solution, but right now I can't see a better one...

**Comment by jimhester** [comment]
Yeah I think adding the API key and a rate limit is the only real option. Does the response include any HTTP headers to tell you when you retry? e.g. https://stackoverflow.com/questions/16022624/examples-of-http-api-rate-limiting-http-response-headers

**Comment by MVesuviusC** [comment]
Well, so here is code I  used to trigger the rate limit so I could look at the response:
```
fetch_url = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi'

query=list(db='nuccore', rettype='fasta', retmode='text', id='555')

for(i in 1:20) { # do it 20 times quickly to trigger the rate limit
  response = POST(fetch_url, body = query)
}
```

If I look at response$headers I get:

```
> response$headers
$`date`
[1] "Tue, 22 Jan 2019 17:07:07 GMT"

$server
[1] "Finatra"

$`strict-transport-security`
[1] "max-age=31536000; includeSubDomains; preload"

$`content-security-policy`
[1] "upgrade-insecure-requests"

$`x-ratelimit-remaining`
[1] "0"

$`l5d-success-class`
[1] "1.0"

$`content-encoding`
[1] "gzip"

$`x-ratelimit-limit`
[1] "3"

$`content-length`
[1] "105"

$`content-type`
[1] "application/json"

$`retry-after`
[1] "2"

$`x-ua-compatible`
[1] "IE=Edge"

$`x-xss-protection`
[1] "1; mode=block"

attr(,"class")
[1] "insensitive" "list" 
```
which gives the query limit value and a few other numbers, and 

```
> rawToChar(response$content)
[1] "{\"error\":\"API rate limit exceeded\",\"api-key\":\"134.192.135.254\",\"count\":\"15\",\"limit\":\"3\"}\n"
```
gives most of the same info but in a more concise form

Have a look at my fork to see if you like how I implemented the api key and rate limit [here](https://github.com/MVesuviusC/primerTree/tree/fixNcbiRateLimitIssue)

**Comment by jimhester** [comment]
We could maybe just respect the `retry-after` header, for this example it seems to be 2 seconds

**Comment by MVesuviusC** [comment]
Potentially, though that portion of the header is only included after you hit the limit. Changing the code above a bit:
```
fetch_url = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi'
query=list(db='nuccore', rettype='fasta', retmode='text', id='555')
response <- list()

for(i in 1:20) { # do it 20 times quickly to trigger the rate limit
  response[[i]] = POST(fetch_url, body = query)
}

# Query number 1 has not hit the limit
response[[1]]$headers$`retry-after` 
## NULL

# Query number 20 has hit the limit
response[[20]]$headers$`retry-after` [1] 
## "2" 
```

We could instead look at the "x-ratelimit-remaining".
```
response[[1]]$headers$`x-ratelimit-remaining` [1] 
## "2" 

response[[20]]$headers$`x-ratelimit-remaining` [1] 
## "0"
```

**Comment by jimhester** [comment]
The idea would be to modify POST_retry to only sleep when there is a retry-after header, e.g.

```r
retry_after <- headers(response)[["retry-after"]] 
if (!is.null(retry_after)) {
  Sys.sleep(retry_after)
}
```

**Comment by MVesuviusC** [comment]
That would work. The only downside is that when you hit the query limit they block you for 2 seconds. This is slower than just submitting a query every 0.33 seconds, at least based on this test:

```
fetch_url = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi'
query=list(db='nuccore', rettype='fasta', retmode='text', id='555')
time1 <- list()
time2 <- list()

for(j in 1:20) {
  response <- list()
  start <- Sys.time()
  for(i in 1:20) { # do it 20 times quickly to trigger the rate limit
    response[[i]] = POST(fetch_url, body = query)
    retry_after <- headers(response[[i]])[["retry-after"]]
    if (!is.null(retry_after)) {
      Sys.sleep(retry_after)
    }
  }
  end <- Sys.time()
  
  time1[[j]] <- end - start
  
  response <- list()
  start <- Sys.time()
  for(i in 1:20) { # do it 20 times quickly to trigger the rate limit
    response[[i]] = POST(fetch_url, body = query)
    Sys.sleep(0.33)
  }
  end <- Sys.time()
  
  time2[[j]] <- end - start
}

mean(as.numeric(time1))
[1] 11.33635  # using retry_after
mean(as.numeric(time2))
[1] 7.50445 # submitting every 0.33 seconds
```
The implementation I did was if there was no api_key provided to query once every 1/3 second, and if there was, query every 1/10 seconds.

**Comment by drdozer** [comment]
I'm hitting essentially this problem. I'm getting the stack-trace below. I don't know how to address this problem from within my script. The 429 error means that _open bails rather than retrying with a delay. It doesn't look for a Retry-After header, for example. It means my full workflow will randomly fail which is sad since it takes up to half an hour to run.

```
  File "/home/nmrp3/.local/lib/python3.7/site-packages/Bio/Entrez/__init__.py", line 195, in efetch
    return _open(cgi, variables, post=post)
  File "/home/nmrp3/.local/lib/python3.7/site-packages/Bio/Entrez/__init__.py", line 555, in _open
    handle = _urlopen(cgi)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
```
