### ISSUE TITLE
Custom database for blast

### ISSUE THREAD

**Issue by alexandracarrier** [MVesuviusC/primerTree#42]
Hello,
Is it possible to use a custom database for blast when using search_primer_pair?
I tried using PRIMER_SPECIFICITY_DATABASE without any luck.

Thanks
Alexandra

**Comment by jamiesone** [comment]
Hello,

I'm having the same issue.... Did you have any luck @alexandracarrier ? Or does anyone have any ideas?

Thanks in advance,
Emily

**Comment by alexandracarrier** [comment]
Never worked for me. Sorry.

**Comment by MVesuviusC** [comment]
I don't think this is possible. The primerBlast search is done remotely on NCBI's servers, so providing a local custom database won't work. What are you trying to accomplish with the custom database?

**Comment by alexandracarrier** [comment]
For me it was to use a custom genome as database, which is not available yet at NCBI.
