### ISSUE TITLE
search_primer_pair does not work with my primers

### ISSUE THREAD

**Issue by rogeriobioinfo** [MVesuviusC/primerTree#43]
**Dears,

I try:**
search_primer_pair('CTTGGTCATTTAGAGGAAGTAA','TCCTCCGCTTATTGATATGC',num_aligns = 10,num_permutations = 25, TOTAL_MISMATCH_IGNORE = 1)

**And the results were:**

BLASTing 1 primer combinations
Submitting Primer-BLAST query
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment completed in 52 seconds
10 BLAST alignments parsed in 0 seconds
taxonomy retrieved in 1 seconds
Warning in get_sequences(primer_search$BLAST_result$gi, primer_search$BLAST_result$product_start,  :
  Sequence retrieval limited to 3 per second. Provide an api_key to increase this to 10. See:
  https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/
10 sequences retrieved from NCBI in 5 seconds, product length min:439 mean:539.4 max:690
Error in system(paste(exec, "--help"), intern = TRUE) : 
  'clustalo' not found
Além disso: Warning messages:
1: In POST_retry(fetch_url, body = query) :
  request failed, retry attempt 1
2: In POST_retry(fetch_url, body = query) :
  request failed, retry attempt 2
> 

**I think so that some links are desatulized in the package**

best regards,
Rogério

**Comment by MVesuviusC** [comment]
Hi Roger, the error message seems to suggest that the command can't find the clustalo program in your path. Do you have this program installed and added to your path?

**Comment by rogeriobioinfo** [comment]
Hi MVesuviusC,

It is my frist time using primerTree,
I did not find any information on documentation about previous local software installations for alignment task,
I understood that alignments were performed online on Clustal Omega.

Rogério

**Comment by MVesuviusC** [comment]
Ah, no worries. The alignment is done locally using clustal omega, so it needs to be installed. Here are some instructions on how to do that: [https://github.com/jimhester/primerTree#clustal-omega-installation](https://github.com/jimhester/primerTree#clustal-omega-installation )

**Comment by rogeriobioinfo** [comment]
MVesuviusC,

Thank you so much!

Rogério
