### ISSUE TITLE
parse_primer_hits does not work with my results

### ISSUE THREAD

**Issue by rogeriobioinfo** [MVesuviusC/primerTree#44]
Hi guys,

I have this simple script:

result <- primer_search('CTTGGTCATTTAGAGGAAGTAA','TCCTCCGCTTATTGATATGC',num_aligns = 10, TOTAL_MISMATCH_IGNORE = 1)

data <-parse_primer_hits(result)

But, the result of primer_search is not recognized by parse_primer_hits, the reported error is:

Error in content(response, as = "text", encoding = "UTF-8") : 
  is.response(x) is not TRUE 

thank you for any help,
Rogério

**Comment by MVesuviusC** [comment]
Hello again, you shouldn't have to call parse_primer_hits() as that is run automatically inside of primer_search(). Is there a particular reason for doing this? If you need to call it for some reason you need to pass the response to the function like:
```
parse_primer_hits(mammals_16S$response[[1]])
```
Be aware that if you have primers with ambiguous bases the $response list will contain one element for each combination blasted, so you'd need to loop through them to get all the data.

**Comment by rogeriobioinfo** [comment]
Hello Matt, 

My reason for doing it:  to get the NCBI accession for each amplified product.

The follow command works to me:

data <- ldply(result, parse_primer_hits)

thank you

**Comment by MVesuviusC** [comment]
You can also do this: 
```
accessions <- names(mammals_16S$sequence)
```
