### ISSUE TITLE
Error in `[.data.frame`(hits, location_columns) : undefined columns selected

### ISSUE THREAD

**Issue by jr2ames** [MVesuviusC/primerTree#46]
Hello:

I have yet to figure out the source of this error. As recently as three weeks ago I had the package working. I tried using `traceback()` and reading the documentation but I didn't get very far. It would seem there is something wrong in the way the response from the BLAST server is processed. Please advise.

Input:
```{r}
mammals_16S = search_primer_pair(name='Mammals 16S', 'CGGTTGGGGTGACCTCGGA',
'GCTGTTATCCCTAGGGTAACT', clustal_options=c(exec = myExecPath))
mammals_16S
```
Output:
```
BLASTing 1 primer combinations
Submitting Primer-BLAST query
BLAST alignment completed in 0 seconds
Error in `[.data.frame`(hits, location_columns) : 
  undefined columns selected
 
Name:  Mammals 16S 
   Arguments:  forward:CGGTTGGGGTGACCTCGGA reverse:GCTGTTATCCCTAGGGTAACT name:Mammals 16S num_aligns:500 num_permutations:25 simplify:TRUE clustal_options.exec:myExecPath 

HTTP Response
Response [https://www.ncbi.nlm.nih.gov/tools/primer-blast/primertool.cgi]
  Date: 2021-01-25 21:00
  Status: 200
  Content-Type: text/html
  Size: 9.18 kB
﻿<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="ncbitoggler" content="animation:'none'"/>
<meta name="referrer" content="origin-when-cross-origin" />
<meta name="ncbi_app" content="primerblast" />
<meta name="ncbi_pdid" content="blastresults" />
<meta name="ncbi_program" content="blastn" />
<meta name="ncbi_db" content="" />
...

Primer Products
NULL

Aligned Products
NULL

Phylogenetic Tree
NULL
```

**Comment by MVesuviusC** [comment]
This looks like a problem on NCBI's end. I get the same message. How long have you been getting this message?

**Comment by jr2ames** [comment]
> This looks like a problem on NCBI's end. I get the same message. How long have you been getting this message?

I have been getting this message since Thursday (1/21), but more than a week had passed since I had last used primerTree.

**Comment by MVesuviusC** [comment]
I would assume that it's an issue with NCBI. The response usually looks like
```
> mammals_16S$response
$`1`
Response [http://www.ncbi.nlm.nih.gov/tools/primer-blast/primertool.cgi?ctg_time=1384796664&job_key=JSID_01_64137_130.14.18.128_9001_primertool]
  Date: NULL
  Status: 200
  Content-Type: text/html
  Size: 420 kB
.
.
.
```
where you can go to that http address to see the results directly. Here we're seeing "https://www.ncbi.nlm.nih.gov/tools/primer-blast/primertool.cgi" which isn't a real response. I don't know why it's still returning a 200 response... I also tried with an api_key and got the same thing.... Give it a few days and see if it straightens itself out I guess unless Jim has other ideas?

**Comment by jr2ames** [comment]
I am still getting this message. I plan to reach out to NCBI.

**Comment by jr2ames** [comment]
I reached out to Wayne Matten at NCBI and he advised that Primer-BLAST had been updated as to require a taxonomic node in the Organism field. By reverting this change if the user supplies only primers, the problem seems to be fixed—primerTree appears to be working properly.

**Comment by MVesuviusC** [comment]
Thanks for following up Jesse! That's very helpful.
