### ISSUE TITLE
primerTree is broken

### ISSUE THREAD

**Issue by cement-head** [MVesuviusC/primerTree#51]
> mammals_16S = search_primer_pair(name='Mammals 16S', 'CGGTTGGGGTGACCTCGGA', 'GCTGTTATCCCTAGGGTAACT')
BLASTing 1 primer combinations
Submitting Primer-BLAST query
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment completed in 111 seconds
500 BLAST alignments parsed in 0 seconds
Error in data.frame(gi = names(taxids), taxId = taxids, stringsAsFactors = FALSE) : 
  row names contain missing values

**Comment by cement-head** [comment]
*bump*

**Comment by MVesuviusC** [comment]
Hi, this is on my to-do list. Thanks for submitting the issue.

**Comment by MVesuviusC** [comment]
This issue should be resolved in the latest release. You can install directly from github using `devtools::install_github()`. The cran release will be updated sometime soon. Let me know if the issue persists.

**Comment by bylemansj** [comment]
Hey Matt, I was just digging up some old code to run some tests on multiple primer combinations. I installed the newest version directly from github but keep on bumping into the same error as reported here. It is not very consistent though, sometimes it runs smoothly but sometimes it throws back the error message. If there are any fixes to this feel free to let me know.
