### ISSUE TITLE
Bad Request (HTTP 400)

### ISSUE THREAD

**Issue by babinecha** [MVesuviusC/primerTree#52]
Hello,

I'm trying search_primer_pair, but returns the following:

BLASTing 1 primer combinations
Submitting Primer-BLAST query
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment processing, refreshing in 20 seconds...
BLAST alignment completed in 115 seconds
500 BLAST alignments parsed in 0 seconds
Error in fetch_taxonomy(unique(taxids)) : Bad Request (HTTP 400).
In addition: Warning messages:
1: In POST_retry(fetch_url, body = query) :
  request failed, retry attempt 1
2: In POST_retry(fetch_url, body = query) :
  request failed, retry attempt 2
3: In POST_retry(fetch_url, body = query) :
  request failed, retry attempt 3
4: In POST_retry(fetch_url, body = query) :
  request failed, retry attempt 4
5: In POST_retry(fetch_url, body = query) :
  request failed, retry attempt 5

**Comment by MVesuviusC** [comment]
Hi, I'm working on a fix for this. It relates to NCBI dropping gi numbers. I hope to have an updated version soon.

**Comment by MVesuviusC** [comment]
This issue should be resolved in the latest release. You can install directly from github using `devtools::install_github()`. The cran release will be updated sometime soon. Let me know if the issue persists.

**Comment by babinecha** [comment]
Hi! Now it 's working! Thank you

**Comment by MVesuviusC** [comment]
Glad to hear!
