### ISSUE TITLE
alternative NCBI database

### ISSUE THREAD

**Issue by babinecha** [MVesuviusC/primerTree#53]
Hello,

In the Cannon et al 2016 paper, it is saying that is possible to search primers in alternative databases, like assembled genomes or RefSeq. How can I change the default nucleotide database to search against other NCBI specific databases?

Thank you

**Comment by MVesuviusC** [comment]
Hi, you can include something like `primer_specificity_database = "refseq_mrna"` as an option to search other databases

**Comment by babinecha** [comment]
It worked that way! Thank you
