### ISSUE TITLE
Control size of blast hits?

### ISSUE THREAD

**Issue by MVesuviusC** [MVesuviusC/primerTree#7]
In blasting a couple primer pairs, I seem to have issues with either very short or long blast hits. I have one primer set that gives me a hit 187116bp long, which messes up the alignment and subsequent tree. I have another primer that gives a blast hit of 1bp, and gives me an error message. it would be handy to have a way to screen out blast hits outside of provided size constraints. Examples are below:

> BirdCOI<-search_primer_pair(name="BirdCOI","TTCTCCAACCACAAAGACATTGGCAC","ACGTGGGAGATAATTCCAAATCCTG")
> BLASTing 1 primer combinations
> Submitting Primer-BLAST query
> BLAST alignment processing, refreshing in 20 seconds...
> BLAST alignment processing, refreshing in 20 seconds...
> BLAST alignment processing, refreshing in 20 seconds...
> BLAST alignment processing, refreshing in 20 seconds...
> BLAST alignment processing, refreshing in 20 seconds...
> BLAST alignment completed in 111 seconds
> 500 BLAST alignments parsed in 4 seconds
> taxonomy retrieved in 16 seconds
> Error in from:to : result would be too long a vector
> In addition: Warning messages:
> 1: In max(i) : no non-missing arguments to max; returning -Inf
> 2: In max(i) : no non-missing arguments to max; returning -Inf
> 500 sequences retrieved from NCBI in 413 seconds, product length min:1 mean:744.44 max:747
> Error in file(con, "rb") : cannot open the connection
> In addition: Warning message:
> In file(con, "rb") :
>   cannot open file '/tmp/Rtmpmfnkrk/file29136e363cca.aln': No such file or directory
> 
> trnH<-search_primer_pair(name="trnH","GTTATGCATGAACGTAATGCTC","CGCGCATGGTGGATTCACAATCC")
> BLASTing 1 primer combinations
> Submitting Primer-BLAST query
> BLAST alignment processing, refreshing in 20 seconds...
> BLAST alignment processing, refreshing in 20 seconds...
> BLAST alignment processing, refreshing in 20 seconds...
> BLAST alignment completed in 70 seconds
> 500 BLAST alignments parsed in 4 seconds
> taxonomy retrieved in 15 seconds
> 500 sequences retrieved from NCBI in 101 seconds, product length min:179 mean:821.29 max:187116
> 500 sequences aligned in 518 seconds length:188595
> constructed neighbor joining tree in 2639 seconds
> Warning message:
> In fun(libname, pkgname) : couldn't connect to display ":0"

**Comment by jimhester** [comment]
I am not getting the errors you are getting here, are you using the code from github or from CRAN?  Just run the below to be sure you are using the most recent version.

``` s
library(devtools)
install_packages("jimhester/primerTree")
library(primerTree)
```

I don't think I ever did an update for CRAN from the last bug you had, so it may still be that problem.

``` s
test = search_primer_pair(name="BirdCOI","TTCTCCAACCACAAAGACATTGGCAC","ACGTGGGAGATAATTCCAAATCCTG")
#  BLASTing 1 primer combinations
#  Submitting Primer-BLAST query
#  BLAST alignment processing, refreshing in 20 seconds...
#  BLAST alignment processing, refreshing in 20 seconds...
#  BLAST alignment processing, refreshing in 20 seconds...
#  BLAST alignment processing, refreshing in 20 seconds...
#  BLAST alignment processing, refreshing in 20 seconds...
#  BLAST alignment processing, refreshing in 20 seconds...
#  BLAST alignment processing, refreshing in 20 seconds...
#  BLAST alignment completed in 151 seconds
#  500 BLAST alignments parsed in 1 seconds
#  Loading required package: XML
#  taxonomy retrieved in 11 seconds
#  500 sequences retrieved from NCBI in 144 seconds, product length min:739 mean:745.94 max:747
#  500 sequences aligned in 55 seconds length:747
#  pairwise DNA distances calculated in 0 seconds
#  constructed neighbor joining tree in 0 seconds
```

``` s
trnH<-search_primer_pair(name="trnH","GTTATGCATGAACGTAATGCTC","CGCGCATGGTGGATTCACAATCC")
#  BLASTing 1 primer combinations
#  Submitting Primer-BLAST query
#  BLAST alignment processing, refreshing in 20 seconds...
#  BLAST alignment processing, refreshing in 20 seconds...
#  BLAST alignment processing, refreshing in 20 seconds...
#  BLAST alignment processing, refreshing in 20 seconds...
#  BLAST alignment completed in 90 seconds
#  500 BLAST alignments parsed in 1 seconds
#  taxonomy retrieved in 7 seconds
#  500 sequences retrieved from NCBI in 92 seconds, product length min:179 mean:448.04 max:755
#  500 sequences aligned in 34 seconds length:832
#  pairwise DNA distances calculated in 0 seconds
#  constructed neighbor joining tree in 1 seconds
```

**Comment by MVesuviusC** [comment]
Still no new version of R, but I grabbed the github version and am still getting the same error:
Perhaps there is some dependency that I need to update?

> library(devtools)
> install_github(user='jimhester', repo='primerTree')
> Installing github repo(s) primerTree/master from jimhester
> Installing primerTree.zip from https://github.com/jimhester/primerTree/archive/master.zip
> Installing primerTree
> '/usr/lib64/R/bin/R' --vanilla CMD INSTALL '/tmp/Rtmp0ocDxm/primerTree-master'  \
>   --library='/home/cannonm3/R/x86_64-redhat-linux-gnu-library/3.0' --with-keep.source 
- installing _source_ package 'primerTree' ...
  *\* libs
  gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c read_dna.c -o read_dna.o
  read_dna.c: In function 'rawStreamToDNAbin':
  read_dna.c:127: warning: pointer targets in passing argument 1 of 'Rf_mkChar' differ in signedness
  gcc -m64 -std=gnu99 -shared -L/usr/local/lib64 -o primerTree.so read_dna.o -L/usr/lib64/R/lib -lR
  installing to /home/cannonm3/R/x86_64-redhat-linux-gnu-library/3.0/primerTree/libs
  *\* R
  *\* data
  **\* moving datasets to lazyload DB
  *\* preparing package for lazy loading
  *\* help
  **\* installing help indices
  converting help for package 'primerTree'
    finding HTML links ... done
    accession2gi                            html  
    bryophytes_trnL                         html  
    clustalo                                html  
    get_sequence                            html  
  
    finding level-2 HTML links ... done
  
    get_sequences                           html  
    get_taxonomy                            html  
    gi2taxid                                html  
    identify.primerTree_plot                html  
    layout_tree_ape                         html  
    mammals_16S                             html  
    plot.primerTree                         html  
    plot_tree                               html  
    plot_tree_ranks                         html  
    primerTree                              html  
    primer_search                           html  
    search_primer_pair                      html  
    summary.primerTree                      html  
    tree_from_alignment                     html  
  *\* building package indices
  *\* testing if installed package can be loaded
- DONE (primerTree)
  > library(primerTree)
  Loading required package: directlabels
  Loading required package: grid
  Loading required package: gridExtra

> test = search_primer_pair(name="BirdCOI","TTCTCCAACCACAAAGACATTGGCAC","ACGTGGGAGATAATTCCAAATCCTG")
> BLASTing 1 primer combinations
> Submitting Primer-BLAST query
> BLAST alignment processing, refreshing in 20 seconds...
> BLAST alignment processing, refreshing in 20 seconds...
> BLAST alignment processing, refreshing in 20 seconds...
> BLAST alignment processing, refreshing in 20 seconds...
> BLAST alignment processing, refreshing in 20 seconds...
> BLAST alignment completed in 110 seconds
> 500 BLAST alignments parsed in 2 seconds
> taxonomy retrieved in 11 seconds
> Error in from:to : result would be too long a vector
> In addition: Warning messages:
> 1: In max(i) : no non-missing arguments to max; returning -Inf
> 2: In max(i) : no non-missing arguments to max; returning -Inf
> Error in from:to : result would be too long a vector
> In addition: Warning messages:
> 1: In max(i) : no non-missing arguments to max; returning -Inf
> 2: In max(i) : no non-missing arguments to max; returning -Inf
> Error in from:to : result would be too long a vector
> In addition: Warning messages:
> 1: In max(i) : no non-missing arguments to max; returning -Inf
> 2: In max(i) : no non-missing arguments to max; returning -Inf
> Error in from:to : result would be too long a vector
> In addition: Warning messages:
> 1: In max(i) : no non-missing arguments to max; returning -Inf
> 2: In max(i) : no non-missing arguments to max; returning -Inf
> Error in from:to : result would be too long a vector
> In addition: Warning messages:
> 1: In max(i) : no non-missing arguments to max; returning -Inf
> 2: In max(i) : no non-missing arguments to max; returning -Inf
> Error in from:to : result would be too long a vector
> In addition: Warning messages:
> 1: In max(i) : no non-missing arguments to max; returning -Inf
> 2: In max(i) : no non-missing arguments to max; returning -Inf
> Error in from:to : result would be too long a vector
> In addition: Warning messages:
> 1: In max(i) : no non-missing arguments to max; returning -Inf
> 2: In max(i) : no non-missing arguments to max; returning -Inf
> 500 sequences retrieved from NCBI in 2249 seconds, product length min:1 mean:735.51 max:747
> Error in file(con, "rb") : cannot open the connection
> In addition: Warning message:
> In file(con, "rb") :
>   cannot open file '/tmp/Rtmp0ocDxm/file119a4a5d7ad2.aln': No such file or directory
> 
> names(test)
> [1] "arguments"    "BLAST_result" "name"         "response"     "sequence"     "taxonomy"

**Comment by MVesuviusC** [comment]
> test_sequences = get_sequences(test$BLAST_result$gi,test$BLAST_result$product_start, test$BLAST_result$product_stop) 
> Error in from:to : result would be too long a vector
> In addition: Warning messages:
> 1: In max(i) : no non-missing arguments to max; returning -Inf
> 2: In max(i) : no non-missing arguments to max; returning -Inf
> Error in from:to : result would be too long a vector
> In addition: Warning messages:
> 1: In max(i) : no non-missing arguments to max; returning -Inf
> 2: In max(i) : no non-missing arguments to max; returning -Inf
> print(test_sequences) 
> 500 DNA sequences in binary format stored in a list.

Mean sequence length: 742.954 
   Shortest sequence: 1 
    Longest sequence: 747 

Labels: 292389662 292389542 292389474 292389282 292389256 292389070 ...

Base composition:
    a     c     g     t 
0.258 0.322 0.166 0.254 

also...

> summary(test_sequences)
>           Length Class  Mode  
> 292389662 746    -none- raw  
> 292389542 746    -none- raw  
> ###cut out a bunch here  
> 292389164 747    -none- raw  
> 292389152 747    -none- raw  
> 292389138 747    -none- raw  
> 292389116   1    -none- logical #<- don't think this is right.....

**Comment by MVesuviusC** [comment]
started new R session and did rm(list=ls()), still looks the same.

get_sequences

function(gi, start=NULL, stop=NULL, simplify=TRUE, .parallel=FALSE, .progress='none'){
  #expand arguments by recycling
  args = expand_arguments(gi=gi, start=start, stop=stop)
  #assign expanded arguments to actual arguments
  lapply(seq_along(args), function(i) names(args)[i] <<- args[i])

  size = length(gi)
  get_sequence_itr = function(i){
    sequence = get_sequence(gi[i], start[i], stop[i])
  }
  sequences = alply(seq_along(gi), .margins=1, .parallel=.parallel, .progress=.progress, failwith(NA, f=get_sequence_itr))
  names = if(simplify) gi else laply(sequences, names)
  sequences = llply(sequences, `[[`, 1)
  names(sequences) = names
  class(sequences) = 'DNAbin'
  sequences
}
<environment: namespace:primerTree>

**Comment by jimhester** [comment]
The only thing I can think of is some connections are failing for some reason, but I don't really have any way to figure out why as I cannot reproduce the error. :-/

**Comment by MVesuviusC** [comment]
Yeah, I'm not sure what the issue is, and if you're not getting the error it's something specific to our servers. Maybe as things update on our end it'll start working again sometime. Thanks for the help.

Date: Thu, 30 Jan 2014 06:38:41 -0800
